# Baseline Keyword Search (TF-IDF)

This notebook implements a traditional keyword-based retrieval system
using TF-IDF vectorization and cosine similarity.

This will later be compared with semantic embedding search.

## Importing Libraries

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

## Loading Processed Data

In [2]:
df = pd.read_csv("../data/processed/movies_semantic.csv")
df.head()

,id,title,semantic_text,vote_average
0,19995,Avatar,Title: Avatar. Tagline: Enter the World of Pan...,7.2
1,285,Pirates of the Caribbean: At World's End,Title: Pirates of the Caribbean: At World's En...,6.9
2,206647,Spectre,Title: Spectre. Tagline: A Plan No One Escapes...,6.3
3,49026,The Dark Knight Rises,Title: The Dark Knight Rises. Tagline: The Leg...,7.6
4,49529,John Carter,Title: John Carter. Tagline: Lost in our world...,6.1

In [3]:
df.shape

(4800, 4)

## Creating TF-IDF Vectorizer

In [4]:
vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=10000
)

In [5]:
tfidf_matrix = vectorizer.fit_transform(df['semantic_text'])

In [6]:
tfidf_matrix.shape

(4800, 10000)

## Building Search Function

In [8]:
def keyword_search(query, top_n=5):
    query_vec = vectorizer.transform([query])
    
    similarities = cosine_similarity(query_vec, tfidf_matrix)
    
    top_indices = similarities[0].argsort()[-top_n:][::-1]
    
    results = df.iloc[top_indices][['title', 'vote_average']]
    
    return results

## Testing Function

In [13]:
keyword_search("unique alien mission")

                title  vote_average
0              Avatar           7.2
972          The Host           6.0
539        Titan A.E.           6.3
373   Mission to Mars           5.7
1201        Predators           6.0

In [14]:
keyword_search("italian mafia family business")

                           title  vote_average
806   Captain Corelli's Mandolin           5.5
3535              Mambo Italiano           5.6
1225            Mickey Blue Eyes           5.3
3336               The Godfather           8.4
1466         Unfinished Business           5.0

In [15]:
keyword_search("loneliness in space")

                             title  vote_average
3729                         Cargo           5.9
1531                     Moonraker           5.9
461                  Lost in Space           5.0
1951                    Space Dogs           6.3
1709  Space Pirate Captain Harlock           6.5

##### Test shows it clearly matches the words but ignores the emotional tone