# Semantic Search using Sentence Embeddings

This notebook implements meaning-based retrieval
using dense vector embeddings and cosine similarity.

In [2]:
# Installing sentence-transformers

In [1]:
import sys
!{sys.executable} -m pip install sentence-transformers

Collecting sentence-transformers
  Using cached sentence_transformers-5.2.3-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (5.2.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (1.4.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (2.10.0)
Requirement already satisfied: numpy in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (2.2.4)
Requirement already satisfied: scikit-learn in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (1.15.2)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (4.14.0)
Requirement already satisfied: tqdm in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging>=20.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.2.19)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: shellingham in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: anyio in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.9.0)
Requirement already satisfied: certifi in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2025.6.15)
Requirement already satisfied: httpcore==1.* in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: setuptools in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: typer>=0.24.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from typer-slim->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.1)
Requirement already satisfied: click>=8.2.1 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from typer>=0.24.0->typer-slim->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from typer>=0.24.0->typer-slim->transformers<6.0.0,>=4.41.0->sentence-transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from typer>=0.24.0->typer-slim->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\utsab\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Using cached sentence_transformers-5.2.3-py3-none-any.whl (494 kB)
Installing collected packages: sentence-transformers
Successfully installed sentence-transformers-5.2.3

WARNING: Ignoring invalid distribution ~ip (C:\Users\Utsab\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\Utsab\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\Utsab\AppData\Local\Programs\Python\Python313\Lib\site-packages)

In [15]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
##Genres list

In [16]:
GENRES = [
    "Action", "Adventure", "Animation", "Comedy", "Crime",
    "Drama", "Family", "Fantasy", "History", "Horror",
    "Music", "Mystery", "Romance", "Science Fiction",
    "Thriller", "War", "Western"
]

## Loading Processed Data

In [17]:
df = pd.read_csv("../data/processed/movies_semantic.csv")
df.shape

(4803, 5)

In [18]:
df['genres_clean'] = df['genres_clean'].fillna('')
df['semantic_text'] = df['semantic_text'].astype(str)

In [19]:
df.isnull().sum()

id               0
title            0
semantic_text    0
genres_clean     0
vote_average     0
dtype: int64

## Loading Pretrained Embedding Model

In [3]:
model = SentenceTransformer('all-MiniLM-L6-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

##### THis converts text into 384-dimensional dense vectors

## Generating Movie Embeddings

In [9]:
movie_embeddings = model.encode(
    df['semantic_text'].tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/151 [00:00<?, ?it/s]

In [10]:
movie_embeddings.shape

(4803, 384)

## Saving Embeddings

In [11]:
np.save("../data/processed/movie_embeddings.npy", movie_embeddings)

## Building Semantic Search Function

In [20]:
def semantic_search(query, top_n=5):
    query_embedding = model.encode([query])
    
    similarities = cosine_similarity(query_embedding, movie_embeddings)
    
    top_indices = similarities[0].argsort()[-top_n:][::-1]
    
    results = df.iloc[top_indices][['title', 'vote_average']]
    
    return results

### detects genres

In [21]:
def detect_genres(query):
    detected = []
    for genre in GENRES:
        if genre.lower() in query.lower():
            detected.append(genre)
    return detected

## Smart Hybrid Search

In [22]:
def hybrid_search(query, top_n=5):
    detected_genres = detect_genres(query)
    
    if detected_genres:
        # Filter by detected genres
        mask = df['genres_clean'].apply(
            lambda x: any(g in x for g in detected_genres)
        )
        
        filtered_indices = df[mask].index
        filtered_embeddings = movie_embeddings[filtered_indices]
        
        query_embedding = model.encode([query])
        similarities = cosine_similarity(query_embedding, filtered_embeddings)
        
        top_indices = similarities[0].argsort()[-top_n:][::-1]
        selected_indices = filtered_indices[top_indices]
        
        return df.loc[selected_indices][['title', 'vote_average']]
    
    else:
        # No genre detected → normal semantic search
        return semantic_search(query, top_n)

In [22]:
semantic_search("loneliness in space")

                  title  vote_average
4515  The Station Agent           7.4
239             Gravity           7.3
95         Interstellar           8.1
778           Meet Dave           5.0
3729              Cargo           5.9

In [23]:
semantic_search("science fiction space isolation survival")

                         title  vote_average
461              Lost in Space           5.0
1198  Escape from Planet Earth           5.7
1531                 Moonraker           5.9
56            Star Trek Beyond           6.6
239                    Gravity           7.3

In [24]:
semantic_search(
    "a science fiction movie about astronauts isolated in deep space struggling to survive"
)

                         title  vote_average
239                    Gravity           7.3
1531                 Moonraker           5.9
1198  Escape from Planet Earth           5.7
643              Space Cowboys           6.3
2757      The Astronaut Farmer           6.2

In [25]:
semantic_search("a science fiction movie about space mission and father-daughter relationship")

                       title  vote_average
1473    The Astronaut's Wife           5.4
4190     Under the Same Moon           7.0
141          Mars Needs Moms           5.5
3355  Flirting with Disaster           6.3
95              Interstellar           8.1

In [26]:
semantic_search("a highly motivating boxing story")

                     title  vote_average
1295     Against the Ropes           4.5
4331                 Rocky           7.5
380         Cinderella Man           7.3
4617  Fighting Tommy Riley           5.3
2916           The Fighter           7.2

#### Duplicating tf-idf vectorization for comparing the results

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer(stop_words='english', max_features=10000)
tfidf_matrix = vectorizer.fit_transform(df['semantic_text'])

def keyword_search(query, top_n=5):
    query_vec = vectorizer.transform([query])
    similarities = cosine_similarity(query_vec, tfidf_matrix)
    top_indices = similarities[0].argsort()[-top_n:][::-1]
    return df.iloc[top_indices][['title', 'vote_average']]

# System Evaluation & Comparison

In [24]:
evaluation_queries = [
    "loneliness in space",
    "italian mafia family business",
    "emotional father daughter relationship",
    "highly motivating boxing story",
    "romantic high school comedy",
    "war survival movie",
    "psychological thriller with mystery",
    "underdog sports drama"
]

In [25]:
for query in evaluation_queries:
    print("\n==============================")
    print("Query:", query)
    
    print("\nTF-IDF:")
    print(keyword_search(query))
    
    print("\nSemantic:")
    print(semantic_search(query))
    
    print("\nHybrid:")
    print(hybrid_search(query))

==============================
Query: loneliness in space

TF-IDF:
               title  vote_average
1531       Moonraker           5.9
461    Lost in Space           5.0
2198         Lockout           5.8
4332  Silent Running           6.3
239          Gravity           7.3

Semantic:
                  title  vote_average
4518  The Station Agent           7.4
239             Gravity           7.3
95         Interstellar           8.1
778           Meet Dave           5.0
365             Contact           7.2

Hybrid:
                  title  vote_average
4518  The Station Agent           7.4
239             Gravity           7.3
95         Interstellar           8.1
778           Meet Dave           5.0
365             Contact           7.2

==============================
Query: italian mafia family business

TF-IDF:
                    title  vote_average
3536       Mambo Italiano           5.6
3337        The Godfather           8.4
1225     Mickey Blue Eyes           5.3
1466  Unfinished Business           5.0
3859      Lords of London           3.6

Semantic:
                        title  vote_average
3337            The Godfather           8.4
3536           Mambo Italiano           5.6
1537               Get Shorty           6.4
867   The Godfather: Part III           7.1
1558             Analyze This           6.4

Hybrid:
                       title  vote_average
1363                Spy Kids           5.5
2464  The Master of Disguise           3.7
989           Baby's Day Out           5.8
118              Ratatouille           7.5
2570       Ramona and Beezus           6.1

==============================
Query: emotional father daughter relationship

TF-IDF:
                                   title  vote_average
3345                   Definitely, Maybe           6.7
3413      House at the End of the Street           5.6
3278  When Did You Last See Your Father?           6.9
1832                            Chocolat           6.8
3588                         Eve's Bayou           6.1

Semantic:
                                   title  vote_average
2146                      The Stepfather           5.4
1292                   Because I Said So           5.8
3278  When Did You Last See Your Father?           6.9
915                              Stepmom           6.9
2000                   Anywhere But Here           5.9

Hybrid:
                                   title  vote_average
2146                      The Stepfather           5.4
1292                   Because I Said So           5.8
3278  When Did You Last See Your Father?           6.9
915                              Stepmom           6.9
2000                   Anywhere But Here           5.9

==============================
Query: highly motivating boxing story

TF-IDF:
              title  vote_average
1307  The Hurricane           7.2
1960   Rocky Balboa           6.5
4727   Penitentiary           4.9
2905         Snatch           7.7
548      Snake Eyes           5.8

Semantic:
               title  vote_average
4333           Rocky           7.5
380   Cinderella Man           7.3
2917     The Fighter           7.2
1327           Creed           7.3
1920         Warrior           7.7

Hybrid:
               title  vote_average
4333           Rocky           7.5
380   Cinderella Man           7.3
2917     The Fighter           7.2
1327           Creed           7.3
1920         Warrior           7.7

==============================
Query: romantic high school comedy

TF-IDF:
                    title  vote_average
1119       21 Jump Street           6.7
3731  High School Musical           6.1
1816       The Best of Me           7.2
2330           Mean Girls           6.9
3218             The DUFF           6.8

Semantic:
                    title  vote_average
3915             Trippin'           4.5
2392             Superbad           7.0
1061        Love Actually           7.0
3266                 Prom           5.7
4024  The Spectacular Now           6.8

Hybrid:
                    title  vote_average
3915             Trippin'           4.5
2392             Superbad           7.0
1061        Love Actually           7.0
3266                 Prom           5.7
4024  The Spectacular Now           6.8

==============================
Query: war survival movie

TF-IDF:
                  title  vote_average
3068        Rescue Dawn           6.9
642            Unbroken           7.3
2194     Disaster Movie           3.0
4311      Extreme Movie           3.9
1282  The Hunting Party           6.6

Semantic:
                                       title  vote_average
1158                           Lone Survivor           7.4
3436                           The Messenger           7.1
582                      Battle: Los Angeles           5.5
4276                               Def-Con 4           2.8
3203  Ultramarines: A Warhammer 40,000 Movie           5.2

Hybrid:
                    title  vote_average
1158        Lone Survivor           7.4
2585      The Hurt Locker           7.2
3068          Rescue Dawn           6.9
456                  Fury           7.4
628   Saving Private Ryan           7.9

==============================
Query: psychological thriller with mystery

TF-IDF:
                                  title  vote_average
3042                           The Gift           6.7
1773                        Mindhunters           6.3
1508                      The Number 23           6.3
4190                                May           6.3
2700  The Diving Bell and the Butterfly           7.4

Semantic:
                 title  vote_average
2267        Regression           5.3
1766           Case 39           6.1
1711          Identity           7.1
4137  Grave Encounters           6.1
3204      The I Inside           5.9

Hybrid:
                 title  vote_average
2267        Regression           5.3
1766           Case 39           6.1
1711          Identity           7.1
4137  Grave Encounters           6.1
3204      The I Inside           5.9

==============================
Query: underdog sports drama

TF-IDF:
                          title  vote_average
3527           Chariots of Fire           6.8
308                 Point Break           5.5
1424                 Concussion           7.0
902               Jerry Maguire           6.7
4166  ABCD (Any Body Can Dance)           5.6

Semantic:
                                 title  vote_average
1548  DodgeBall: A True Underdog Story           6.2
2064                         Underdogs           6.0
928                          Moneyball           7.0
2922                      Major League           6.6
1403                The Bad News Bears           6.9

Hybrid:
                 title  vote_average
928          Moneyball           7.0
1327             Creed           7.3
795       Leatherheads           5.7
1424        Concussion           7.0
712   Any Given Sunday           6.8

# Comparative Evaluation

Observations:

1. TF-IDF performs well for exact keyword queries but struggles with conceptual similarity.
2. Semantic search captures thematic and emotional meaning effectively.
3. Hybrid search improves domain-specific queries by combining genre filtering with semantic ranking.
4. For multi-intent queries, hybrid provides the most stable results.